version: "3.9"
   
services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: sh -c "chmod +x /code/migrate.sh && sh /code/migrate.sh && sh /code/entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - rabbitmq

  worker:
      build: 
        context: .
        dockerfile: Dockerfile
      command: celery -A EcpDemo worker -l info
      volumes:
        - .:/code
      depends_on:
        - db
        - web
        - rabbitmq

  beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A EcpDemo beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - web
      - rabbitmq
      - worker
  # Postgis
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # RabbitMQ
  rabbitmq:
    image: rabbitmq
   


